<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.api.framework</groupId>
    <artifactId>restassured-framework</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <!-- ========================================================= -->
    <!-- Properties -->
    <!-- ========================================================= -->

    <properties>

        <!-- Java -->
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Library Versions -->
        <restassured.version>5.4.0</restassured.version>
        <testng.version>7.11.0</testng.version>
        <jackson.version>2.17.1</jackson.version>
        <json.version>20240303</json.version>
        <extentreports.version>5.1.1</extentreports.version>
        <jakarta.mail.version>2.0.1</jakarta.mail.version>

        <!-- Allure -->
        <allure.version>2.35.3</allure.version>

        <!-- Plugins -->
        <maven.compiler.plugin.version>3.13.0</maven.compiler.plugin.version>
        <maven.surefire.plugin.version>3.5.0</maven.surefire.plugin.version>
        <maven.clean.plugin.version>3.4.0</maven.clean.plugin.version>
        <maven.surefire.report.version>3.5.0</maven.surefire.report.version>

    </properties>

    <!-- ========================================================= -->
    <!-- Dependencies -->
    <!-- ========================================================= -->

    <dependencies>

        <!-- REST Assured -->
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>${restassured.version}</version>
        </dependency>

        <!-- TestNG -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>${testng.version}</version>
            
        </dependency>

        <!-- Allure TestNG -->
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-testng</artifactId>
            <version>${allure.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- Jackson -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <!-- JSON -->
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>${json.version}</version>
        </dependency>

        <!-- Extent Reports -->
        <dependency>
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports</artifactId>
            <version>${extentreports.version}</version>
        </dependency>

        <!-- Jakarta Mail -->
        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>jakarta.mail</artifactId>
            <version>${jakarta.mail.version}</version>
        </dependency>

    </dependencies>

    <!-- ========================================================= -->
    <!-- Build -->
    <!-- ========================================================= -->

    <build>

        <plugins>

            <!-- Compiler -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>

                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                </configuration>

            </plugin>

            <!-- TestNG Execution -->
            <plugin>

                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.plugin.version}</version>

                <configuration>

                    <suiteXmlFiles>

                        <suiteXmlFile>testng/testng.xml</suiteXmlFile>

                    </suiteXmlFiles>

                </configuration>

            </plugin>

            <!-- Maven Clean -->
            <plugin>

                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <version>${maven.clean.plugin.version}</version>

            </plugin>

            <!-- Surefire Report -->

            <plugin>

                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-report-plugin</artifactId>
                <version>${maven.surefire.report.version}</version>

            </plugin>

            <!-- Allure Report -->
            <plugin>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-maven</artifactId>
                <version>2.12.0</version>
            </plugin>

        </plugins>

    </build>

</project>